name: Android CI

on:
  push:
    branches:
      - main
    paths:
      - 'app/src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'app/src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/src

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Cache Android SDK
        uses: actions/cache@v3
        with:
          path: ~/.android
          key: ${{ runner.os }}-android-sdk

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Run Lint
        run: ./gradlew lint

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/src/build/outputs/apk/debug/app-debug.apk